apiVersion: v1
kind: Pod
metadata:
 name: mount-secret
spec:
 containers:
   - image: nginx:1.17.0
     name: nginx 
     volumeMounts:
       - name: mount-secret
         mountPath: /etc/secret
         readOnly: true
 volumes: 
  - name: mount-secret
    secret: 
     secretName: basic-auth   
