apiVersion: v1
kind: Pod
metadata:
        name: mypod
        namespace: ckad-prep
spec:
        containers:
        - name: mypod
          image: nginx:1.14
          ports:
          - containerPort: 80        

