# define the deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels:
    app: my-deploy
spec:
  replicas: 3 
  selector: 
   matchLabels: 
    app: nginx
  template: 
   metadata: 
    labels: 
     app: nginx


   spec: 
     containers: 
     - name: nginx 
       image: nginx:1.14.2
       ports: 
       - containerPort: 8080   
        